functionality:
  name: earl_submission
  namespace: predict_modality_starter_kits
  
  # metadata for your method
  version: dev
  description: EaRL is a graph neural network 
  authors:
    - name: Bryan Glazer
      email: bryan.glazer@vanderbilt.edu
      roles: [ author ]
      props: { github: bglazer, orcid: "0000-0002-0434-7672" }
      
  # parameters
  arguments:
    # required inputs
    - name: "--input_train_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset, training cells.
      required: true
    - name: "--input_test_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset, test cells.
      required: true
    - name: "--input_train_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    # required outputs
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
    # Method-specific parameters. Change these to expose parameters of your method to Nextflow (optional)
      
  # files your script needs
  resources:
    - type: python_script
      path: earl_submission_script.py
    - path: latest_earl_20211117-2359.model
    - path: earl_params_20211117-2359.json
    - path: nodes_by_type.pickle
    - path: graph_with_embeddings.torch
  
  # resources for unit testing your component
  tests:

# target platforms
platforms:

  # By specifying 'docker' platform, viash will build a standalone
  # executable which uses docker in the back end to run your method.
  - type: docker
    # you need to specify a base image that contains at least bash and python
    image: bglazer/pyg:v2
    run_args: [ "--gpus all" ]
    # You can specify additional dependencies with 'setup'. 
    # See https://viash.io/docs/reference_config/platform-docker/#setup-list
    # for more information on how to add more dependencies.
    #setup:
    #  - type: python
    #    packages:
    #      - scikit-learn
    #      - anndata
    #      - scanpy

  # By specifying a 'nextflow', viash will also build a viash module
  # which uses the docker container built above to also be able to 
  # run your method as part of a nextflow pipeline.
  - type: nextflow
    labels: [ midmem, hightime, midcpu, gpu ]

  # used for saturn cloud
  - type: native
